### ISSUE TITLE
Wheel marked as arch independent, while being arch dependent

### ISSUE THREAD

**Issue by nouiz** [google/grain#313]
I'm trying to use t5x on a GraceHopper computer that has an ARM based CPU.
T5x depends on grain-nightly and install it from pypi.
`pip install grain-nightly` work on ARM.
But the installed wheel fail at import as it try to load an .so that is build for x86.

Can the wheel be marked as dependent, so that it isn't found and not installed?

Here is a PR that fix the same issue in another project:
https://github.com/google/array_record/pull/79/files

I can't test it as I'm not able to build this project on x86 and on ARM.

**Comment by iindyk** [comment]
Sorry for a delay, indeed the wheels are arch dependent, we added the platform tags and also added the ARM builds to our releases. You should be able to `pip install grain` (`grain-nightly` will also work, but prefer `grain` for stable releases). See

https://pypi.org/project/grain/0.1.0/#files
https://pypi.org/project/grain-nightly/0.0.7/#files
