### ISSUE TITLE
Usage Examples

### ISSUE THREAD

**Issue by leandrolcampos** [google/grain#350]
Where can I find good Grain usage examples?

**Comment by andyehrenberg** [comment]
MaxText seems to have added grain usage: https://github.com/google/maxtext/blob/main/MaxText/input_pipeline/_grain_data_processing.py

**Comment by leandrolcampos** [comment]
Thanks, @andyehrenberg. I'll take a look.

**Comment by aireenmei** [comment]
Hi @leandrolcampos, thanks for reaching out. I've just added some docs: https://github.com/google/grain/tree/main/docs, will add more. And yes, please also refer to maxtext for usage example.

**Comment by leandrolcampos** [comment]
Hi @aireenmei,

Thank you for your swift response and for adding the documentation. I greatly appreciate it. It would be incredibly helpful if the docs could include examples demonstrating the use of Grain in various scenarios, particularly focusing on best practices for employing Grain with different data sources and across diverse distributed input pipeline configurations, such as a single machine with multiple devices and multiple machines, each with multiple devices.

Looking forward to applying Grain in my research projects.

All the best,

**Comment by borisdayma** [comment]
Not sure if it should be filed as a new issue but I have some questions based on the documentation:

1. To have a global index and also associate it to the right shard, does it mean you need the number of elements in each shard, which would be a long operation to access? N that case should it be stored externally maybe in a separate file?
2. Can you access element n of a tfrecord efficiently without reading it sequentially?
3. Is tfrecord still the preferred format?

**Comment by aireenmei** [comment]
Grain does not use TFRecord. It depends on ArrayRecord (https://github.com/google/array_record), which supports random access.
