### ISSUE TITLE
shard_options in IndexSampler

### ISSUE THREAD

**Issue by bgyoon** [google/grain#351]
If shard_options is specified in IndexSampler, isn't the dataset being sharded twice?

DataLoader shards dataset if `hasattr(self._sampler, "_shard_options")` but sampler will shard it again with ShardLazyDataset() since that hasn't been disabled.

https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/samplers.py#L123
https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/data_loader.py#L263

**Comment by iindyk** [comment]
Thanks for reaching out. Sharding only happens once [here](https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/samplers.py#L123).

[This](https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/data_loader.py#L263) does not shard, but merely constructs an initial checkpoint with correct first indices per worker.

**Comment by bgyoon** [comment]
If [next_index is incremented](https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/data_loader.py#L297) by _global_num_workers, isn't it effectively sharding the full set?

For example, if the full set is of size 1000 and _global_num_workers is 10, each worker will read every 10th element.(i.e., step size is 50) until 1000. Each worker will read 100 elements in total. Doesn't that already achieve sharding?

ShardLazyDataset() shards dataset of size 1000 to number of hosts, and gives it offset start and end, making it subset of full set, local to each host. In that case, next_index of each worker should increment by 1 since it's already reading the subset.

Dataloader will shard based on full set index. ShardLazyDataset will shard the full set into local set. Mixing them together , globally sharded indexing from Dataloader will [index elements exceeding](https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/lazy_dataset/lazy_dataset.py#L559) size of local set sharded by ShardLazyDataset.

Also, how come SequentialSampler doesn't use ShardLazyDataset?


Also, how come

**Comment by iindyk** [comment]
Double sharding would be very easy to detect. I tried switching [this test](https://github.com/google/grain/blob/98531edd5332c3f212853f88513ac55f29be96b7/grain/_src/python/data_loader_test.py#L344) to use `samplers.IndexSampler` with `shard_count=3` and DataLoader with `worker_count=10` and as expected I got:

- `[b"0", b"1", b"2", b"3"]` for `shard_index=0`
- `[b"4", b"5", b"6"]` for `shard_index=1`
- `[b"7", b"8", b"9"]` for `shard_index=2`

With `samplers.SequentialSampler` and rest of the params the same I got:

- `[b'0', b'3', b'6', b'9']` for `shard_index=0`
- `[b'1', b'4', b'7']` for `shard_index=1`
- `[b'2', b'5', b'8']` for `shard_index=2`

We should improve our testing coverage but the cases are working as expected. If you think there's a bug with sharding -- please provide us a code snippet to reproduce it.

> Also, how come SequentialSampler doesn't use ShardLazyDataset?

they shard data differently -- see the example above. IndexSampler is more optimized -- the records are not globally ordered across shards which allows better per-shard read locality

**Comment by bgyoon** [comment]
Oh, you're right. I was wrong. Within sampler it's being effectively incremented by 1 since [it's divided by number of shards](https://github.com/google/grain/blob/f58031724ff06bcc84943c9a8ec501c8941dd660/grain/_src/python/samplers.py#L149).

Thank you very much for your answer.
