### ISSUE TITLE
Allow older versions of Orbax

### ISSUE THREAD

**Issue by darsnack** [google/grain#491]
Currently, if an older version of Orbax is used, then grain throws an error when loading:
```
[...]
     81 try:
     82   # Register the handler to be used with the new checkpointing API if Orbax is
     83   # present.
     84   import orbax.checkpoint as ocp  # pylint:disable=g-import-not-at-top # pytype:disable=import-error
---> 86   @ocp.args.register_with_handler(PyGrainCheckpointHandler, for_save=True)  # pytype:disable=wrong-arg-types
     87   @dataclasses.dataclass
     88   class PyGrainCheckpointSave(ocp.args.CheckpointArgs):
     89     item: Any
     91   @ocp.args.register_with_handler(PyGrainCheckpointHandler, for_restore=True)  # pytype:disable=wrong-arg-types
     92   @dataclasses.dataclass
     93   class PyGrainCheckpointRestore(ocp.args.CheckpointArgs):

AttributeError: module 'orbax.checkpoint' has no attribute 'args'
```
This is because this code relies on the [latest version of Orbax](https://orbax.readthedocs.io/en/latest/custom_handlers.html#checkpointhandler).

No need to support the old version, but can you accept an `AttributeError` in the try block so that if the old version is installed, then we skip registering the handlers? This would help those of us who want to use grain for reasons other than checkpointing the data loader.

**Comment by iindyk** [comment]
fixed in https://github.com/google/grain/pull/625
