### ISSUE TITLE
no python3.12 for aarch64

### ISSUE THREAD

**Issue by surak** [google/grain#608]
on pypi, you only have builds for aarch64 for older versions of python, not for 3.12 yet - this for whatever reason is building for x86_64 only.

https://pypi.org/project/grain/#files

```
[grain-0.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ]
[grain-0.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ]
[grain-0.2.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]
[grain-0.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ]
[grain-0.2.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]
[grain-0.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ]
[grain-0.2.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ]
```

**Comment by surak** [comment]
This makes it impossible to use jax-ai-stack[grain] on Nvidia grace hopper hardware.

**Comment by iindyk** [comment]
at the time we released h5py didn't have 3.12 aarch64 wheels and was required by one of the testing deps. if this is blocking your workflow I can make a new release with 3.12 aarch64 support tomorrow or early next week

**Comment by iindyk** [comment]
https://pypi.org/project/grain/0.2.2/#files

**Comment by surak** [comment]
Awesome, thanks!
